env:
  browser: false
  es2021: true
  node: true
extends:
  - eslint:recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 12
  sourceType: module
  ecmaFeatures:
    impliedStrict: true
plugins:
  - "@typescript-eslint"
rules: {}
root: true
noInlineConfig: true
